INSERT INTO `cities` (`province_id`, `name`, `status`) VALUES
(1, 'Kabupaten Aceh Barat', 1),
(1, 'Kabupaten Aceh Barat Daya', 1),
(1, 'Kabupaten Aceh Besar', 1),
(1, 'Kabupaten Aceh Jaya', 1),
(1, 'Kabupaten Aceh Selatan', 1),
(1, 'Kabupaten Aceh Singkil', 1),
(1, 'Kabupaten Aceh Tamiang', 1),
(1, 'Kabupaten Aceh Tengah', 1),
(1, 'Kabupaten Aceh Tenggara', 1),
(1, 'Kabupaten Aceh Timur', 1),
(1, 'Kabupaten Aceh Utara', 1),
(1, 'Kabupaten Bener Meriah', 1),
(1, 'Kabupaten Bireuen', 1),
(1, 'Kabupaten Gayo Lues', 1),
(1, 'Kabupaten Nagan Raya', 1),
(1, 'Kabupaten Pidie', 1),
(1, 'Kabupaten Pidie Jaya', 1),
(1, 'Kabupaten Simeulue', 1),
(1, 'Kota Banda Aceh', 1),
(1, 'Kota Langsa', 1),
(1, 'Kota Lhokseumawe', 1),
(1, 'Kota Sabang', 1),
(1, 'Kota Subulussalam', 1),
(2, 'Kabupaten Asahan', 1),
(2, 'Kabupaten Batu Bara', 1),
(2, 'Kabupaten Dairi', 1),
(2, 'Kabupaten Deli Serdang', 1),
(2, 'Kabupaten Humbang Hasundutan', 1),
(2, 'Kabupaten Karo', 1),
(2, 'Kabupaten Labuhanbatu', 1),
(2, 'Kabupaten Labuhanbatu Selatan', 1),
(2, 'Kabupaten Labuhanbatu Utara', 1),
(2, 'Kabupaten Langkat', 1),
(2, 'Kabupaten Mandailing Natal', 1),
(2, 'Kabupaten Nias', 1),
(2, 'Kabupaten Nias Barat', 1),
(2, 'Kabupaten Nias Selatan', 1),
(2, 'Kabupaten Nias Utara', 1),
(2, 'Kabupaten Padang Lawas', 1),
(2, 'Kabupaten Padang Lawas Utara', 1),
(2, 'Kabupaten Pakpak Bharat', 1),
(2, 'Kabupaten Samosir', 1),
(2, 'Kabupaten Serdang Bedagai', 1),
(2, 'Kabupaten Simalungun', 1),
(2, 'Kabupaten Tapanuli Selatan', 1),
(2, 'Kabupaten Tapanuli Tengah', 1),
(2, 'Kabupaten Tapanuli Utara', 1),
(2, 'Kabupaten Toba', 1),
(2, 'Kota Binjai', 1),
(2, 'Kota Gunungsitoli', 1),
(2, 'Kota Medan', 1),
(2, 'Kota Padang Sidempuan', 1),
(2, 'Kota Pematangsiantar', 1),
(2, 'Kota Sibolga', 1),
(2, 'Kota Tanjungbalai', 1),
(2, 'Kota Tebing Tinggi', 1),
(3, 'Kabupaten Agam', 1),
(3, 'Kabupaten Dharmasraya', 1),
(3, 'Kabupaten Kepulauan Mentawait', 1),
(3, 'Kabupaten Lima Puluh Kota', 1),
(3, 'Kabupaten Padang Pariaman', 1),
(3, 'Kabupaten Pasaman', 1),
(3, 'Kabupaten Pasaman Barat', 1),
(3, 'Kabupaten Pasaman Selatan', 1),
(3, 'Kabupaten Sijunjung', 1),
(3, 'Kabupaten Solok', 1),
(3, 'Kabupaten Solok Selatan', 1),
(3, 'Kabupaten Tanah Datar', 1),
(3, 'Kota Bukittinggi', 1),
(3, 'Kota Padang', 1),
(3, 'Kota Padang Panjang', 1),
(3, 'Kota Pariaman', 1),
(3, 'Kota Payakumbuh', 1),
(3, 'Kota Sawahlunto', 1),
(3, 'Kota Solok', 1),
(4, 'Kabupaten Bengkalis', 1),
(4, 'Kabupaten Indragiri Hilir', 1),
(4, 'Kabupaten Indragiri Hulu', 1),
(4, 'Kabupaten Kampar', 1),
(4, 'Kabupaten Kepulauan Meranti', 1),
(4, 'Kabupaten Kuantan Singingi', 1),
(4, 'Kabupaten Pelalawan', 1),
(4, 'Kabupaten Rokan Hilir', 1),
(4, 'Kabupaten Rokan Hulu', 1),
(4, 'Kabupaten Siak', 1),
(4, 'Kota Dumai', 1),
(4, 'Kota Pekanbaru', 1),
(5, 'Kabupaten Batanghari', 1),
(5, 'Kabupaten Bungo', 1),
(5, 'Kabupaten Tanjung Jabung Barat', 1),
(5, 'Kabupaten Kerinci', 1),
(5, 'Kabupaten Merangin', 1),
(5, 'Kabupaten Muaro Jambi', 1),
(5, 'Kabupaten Sarolangun', 1),
(5, 'Kabupaten Tanjung Jabung Timur', 1),
(5, 'Kabupaten Tebo', 1),
(5, 'Kota Jambi', 1),
(5, 'Kota Sungai Penuh', 1),
(6, 'Kabupaten Banyuasin', 1),
(6, 'Kabupaten Empat Lawang', 1),
(6, 'Kabupaten Lahat', 1),
(6, 'Kabupaten Muara Enim', 1),
(6, 'Kabupaten Musi Banyuasin', 1),
(6, 'Kabupaten Musi Rawas', 1),
(6, 'Kabupaten Musi Rawas Utara', 1),
(6, 'Kabupaten Ogan Ilir', 1),
(6, 'Kabupaten Ogan Komering Ilir', 1),
(6, 'Kabupaten Ogan Komering Ulu', 1),
(6, 'Kabupaten Ogan Komering Ulu Selatan', 1),
(6, 'Kabupaten Ogan Komering Ulu Timur', 1),
(6, 'Kabupaten Penukal Abab Lematang Ilir', 1),
(6, 'Kota Lubuklinggau', 1),
(6, 'Kota Pagar Alam', 1),
(6, 'Kota Palembang', 1),
(6, 'Kota Prabumulih', 1),
(7, 'Kabupaten Bengkulu Selatan', 1),
(7, 'Kabupaten Bengkulu Tengah', 1),
(7, 'Kabupaten Bengkulu Utara', 1),
(7, 'Kabupaten Kaur', 1),
(7, 'Kabupaten Kepahiang', 1),
(7, 'Kabupaten Lebong', 1),
(7, 'Kabupaten Mukomuko', 1),
(7, 'Kabupaten Rejang Lebong', 1),
(7, 'Kabupaten Seluma', 1),
(7, 'Kota Bengkulu', 1),
(8, 'Kabupaten Lampung Selatan', 1),
(8, 'Kabupaten Lampung Tengah', 1),
(8, 'Kabupaten Lampung Timur', 1),
(8, 'Kabupaten Lampung Utara', 1),
(8, 'Kabupaten Mesujia', 1),
(8, 'Kabupaten Pesawaran', 1),
(8, 'Kabupaten Pesisir Barat', 1),
(8, 'Kabupaten Pringsewu', 1),
(8, 'Kabupaten Tanggamus', 1),
(8, 'Kabupaten Tulang Bawang', 1),
(8, 'Kabupaten Tulang Bawang Barat', 1),
(8, 'Kabupaten Way Kanan', 1),
(8, 'Kota Bandar Lampung', 1),
(8, 'Kota Metro', 1),
(9, 'Kabupaten Bangka', 1),
(9, 'Kabupaten Bangka Barat', 1),
(9, 'Kabupaten Bangka Selatan', 1),
(9, 'Kabupaten Bangka Tengah', 1),
(9, 'Kabupaten Belitung', 1),
(9, 'Kabupaten Belitung Timur', 1),
(9, 'Kota Pangkalpinang', 1),
(10, 'Kabupaten Bintan', 1),
(10, 'Kabupaten Karimun', 1),
(10, 'Kabupaten Kepulauan Anamba', 1),
(10, 'Kabupaten Lingga', 1),
(10, 'Kabupaten Natuna', 1),
(10, 'Kota Batam', 1),
(10, 'Kota Tanjungpinang', 1),
(11, 'Jakarta Barat', 1),
(11, 'Jakarta Pusat', 1),
(11, 'Jakarta Selatan', 1),
(11, 'Jakarta Timur', 1),
(11, 'Jakarta Utara', 1),
(12, 'Kabupaten Bandung', 1),
(12, 'Kabupaten Bandung Barat', 1),
(12, 'Kabupaten Bekasi', 1),
(12, 'Kabupaten Bogor', 1),
(12, 'Kabupaten Ciamis', 1),
(12, 'Kabupaten Cianjur', 1),
(12, 'Kabupaten Cirebon', 1),
(12, 'Kabupaten Garut', 1),
(12, 'Kabupaten Indramayu', 1),
(12, 'Kabupaten Karawang', 1),
(12, 'Kabupaten Kuningan', 1),
(12, 'Kabupaten Majalengka', 1),
(12, 'Kabupaten Pangandaran', 1),
(12, 'Kabupaten Purwakarta', 1),
(12, 'Kabupaten Subang', 1),
(12, 'Kabupaten Sukabumi', 1),
(12, 'Kabupaten Sumedang', 1),
(12, 'Kabupaten Tasikmalaya', 1),
(12, 'Kota Bandung', 1),
(12, 'Kota Banjar', 1),
(12, 'Kota Bekasi', 1),
(12, 'Kota Bogor ', 1),
(12, 'Kota Cimahi ', 1),
(12, 'Kota Cirebon ', 1),
(12, 'Kota Depok ', 1),
(12, 'Kota Sukabumi ', 1),
(12, 'Kota Tasikmalaya ', 1),
(13, 'Kabupaten Banjarnegara', 1),
(13, 'Kabupaten Banyumas', 1),
(13, 'Kabupaten Batang', 1),
(13, 'Kabupaten Blora', 1),
(13, 'Kabupaten Boyolali', 1),
(13, 'Kabupaten Brebes', 1),
(13, 'Kabupaten Cilacap', 1),
(13, 'Kabupaten Demak', 1),
(13, 'Kabupaten Grobogan', 1),
(13, 'Kabupaten Jepara', 1),
(13, 'Kabupaten Karanganyar', 1),
(13, 'Kabupaten Kebumen', 1),
(13, 'Kabupaten Kendal', 1),
(13, 'Kabupaten Klaten', 1),
(13, 'Kabupaten Kudus', 1),
(13, 'Kabupaten Magelang', 1),
(13, 'Kabupaten Pati', 1),
(13, 'Kabupaten Pekalongan', 1),
(13, 'Kabupaten Pemalang', 1),
(13, 'Kabupaten Purbalingga', 1),
(13, 'Kabupaten Purworejo', 1),
(13, 'Kabupaten Rembang', 1),
(13, 'Kabupaten Semarang', 1),
(13, 'Kabupaten Sragen', 1),
(13, 'Kabupaten Sukoharjo', 1),
(13, 'Kabupaten Tegal', 1),
(13, 'Kabupaten Temanggung', 1),
(13, 'Kabupaten Wonogiri', 1),
(13, 'Kabupaten Wonosobo', 1),
(13, 'Kota Magelang', 1),
(13, 'Kota Pekalongan', 1),
(13, 'Kota Salatiga', 1),
(13, 'Kota Semarang', 1),
(13, 'Kota Surakarta', 1),
(13, 'Kota Tegal', 1),
(14, 'Kabupaten Bantul', 1),
(14, 'Kabupaten Gunungkidul', 1),
(14, 'Kabupaten Kulon Progo', 1),
(14, 'Kabupaten Sleman', 1),
(14, 'Kota Yogyakarta', 1),
(15, 'Bangkalan', 1),
(15, 'Banyuwangi', 1),
(15, 'Blitar', 1),
(15, 'Bojonegoro', 1),
(15, 'Bondowoso', 1),
(15, 'Gresik', 1),
(15, 'Jember', 1),
(15, 'Jombang', 1),
(15, 'Kediri', 1),
(15, 'Lamongan', 1),
(15, 'Lumajang', 1),
(15, 'Madiun', 1),
(15, 'Magetan', 1),
(15, 'Malang', 1),
(15, 'Mojokerto', 1),
(15, 'Nganjuk', 1),
(15, 'Ngawi', 1),
(15, 'Pacitan', 1),
(15, 'Pamekasan', 1),
(15, 'Pasuruan', 1),
(15, 'Ponorogo', 1),
(15, 'Probolinggo', 1),
(15, 'Sampang', 1),
(15, 'Sidoarjo', 1),
(15, 'Situbondo', 1),
(15, 'Sumenep', 1),
(15, 'Trenggalek', 1),
(15, 'Tuban', 1),
(15, 'Tulungagung', 1),
(15, 'Kota Batu', 1),
(15, 'Kota Blitar', 1),
(15, 'Kota Kediri', 1),
(15, 'Kota Kediri', 1),
(15, 'Kota Madiun', 1),
(15, 'Kota Malang', 1),
(15, 'Kota Mojokerto', 1),
(15, 'Kota Pasuruan', 1),
(15, 'Kota Probolinggo', 1),
(15, 'Kota Surabaya', 1),
(16, 'Kabupaten Lebak', 1),
(16, 'Kabupaten Pandeglang', 1),
(16, 'Kabupaten Serang', 1),
(16, 'Kabupaten Tangerang', 1),
(16, 'Kota Cilegon', 1),
(16, 'Kota Serang', 1),
(16, 'Kota Tangerang', 1),
(16, 'Kota Tangerang Selatan', 1),
(17, 'Kabupaten Badung', 1),
(17, 'Kabupaten Bangli', 1),
(17, 'Kabupaten Buleleng', 1),
(17, 'Kabupaten Gianyar', 1),
(17, 'Kabupaten Jembrana', 1),
(17, 'Kabupaten Karangasem', 1),
(17, 'Kabupaten Klungkung', 1),
(17, 'Kabupaten Tabanan', 1),
(17, 'Kota Denpasar', 1),
(18, 'Kabupaten Bima', 1),
(18, 'Kabupaten Dompu', 1),
(18, 'Kabupaten Lombok Barat', 1),
(18, 'Kabupaten Lombok Tengah', 1),
(18, 'Kabupaten Lombok Timur', 1),
(18, 'Kabupaten Lombok Utara', 1),
(18, 'Kabupaten Sumbawa', 1),
(18, 'Kabupaten Sumbawa Barat', 1),
(18, 'Kota Bima', 1),
(18, 'Kota Mataram', 1),
(19, 'Kabupaten Alor', 1),
(19, 'Kabupaten Belu', 1),
(19, 'Kabupaten Ende', 1),
(19, 'Kabupaten Flores Timur', 1),
(19, 'Kabupaten Kupang', 1),
(19, 'Kabupaten Lembata', 1),
(19, 'Kabupaten Malaka', 1),
(19, 'Kabupaten Manggarai', 1),
(19, 'Kabupaten Manggarai Barat', 1),
(19, 'Kabupaten Manggarai Timur', 1),
(19, 'Kabupaten Nagekeo', 1),
(19, 'Kabupaten Ngada', 1),
(19, 'Kabupaten Rote Ndao', 1),
(19, 'Kabupaten Sabu Raijua', 1),
(19, 'Kabupaten Sikka', 1),
(19, 'Kabupaten Sumba Barat', 1),
(19, 'Kabupaten Sumba Barat Daya', 1),
(19, 'Kabupaten Sumba Tengah', 1),
(19, 'Kabupaten Timor Tengah Selatan', 1),
(19, 'Kabupaten Timor Tengah Utara', 1),
(19, 'Kota Kupang', 1),
(20, 'Kabupaten Bengkayang', 1),
(20, 'Kabupaten Kapuas Hulu', 1),
(20, 'Kabupaten Kayong Utara', 1),
(20, 'Kabupaten Ketapang', 1),
(20, 'Kabupaten Kubu Raya', 1),
(20, 'Kabupaten Landak', 1),
(20, 'Kabupaten Melawi', 1),
(20, 'Kabupaten Mempawah', 1),
(20, 'Kabupaten Sambas', 1),
(20, 'Kabupaten Sanggau', 1),
(20, 'Kabupaten Sekadau', 1),
(20, 'Kabupaten Sintang', 1),
(20, 'Kota Pontianak', 1),
(20, 'Kota Singkawang', 1),
(21, 'Kabupaten Barito Selatan', 1),
(21, 'Kabupaten Barito Timur', 1),
(21, 'Kabupaten Barito Utara', 1),
(21, 'Kabupaten Gunung Mas', 1),
(21, 'Kabupaten Kapuas', 1),
(21, 'Kabupaten Katingan', 1),
(21, 'Kabupaten Kotawaringin Barat', 1),
(21, 'Kabupaten Kotawaringin Timur', 1),
(21, 'Kabupaten Lamandau', 1),
(21, 'Kabupaten Murung Raya', 1),
(21, 'Kabupaten Pulang Pisau', 1),
(21, 'Kabupaten Sukamara', 1),
(21, 'Kabupaten Seruyan', 1),
(21, 'Kota Palangka Raya', 1),
(22, 'Kabupaten Balangan', 1),
(22, 'Kabupaten Banjar', 1),
(22, 'Kabupaten Barito Kuala', 1),
(22, 'Kabupaten Hulu Sungai Selatan', 1),
(22, 'Kabupaten Hulu Sungai Tengah', 1),
(22, 'Kabupaten Hulu Sungai Utara', 1),
(22, 'Kabupaten Kotabaru', 1),
(22, 'Kabupaten Tabalong', 1),
(22, 'Kabupaten Tanah Bumbu', 1),
(22, 'Kabupaten Tanah Laut', 1),
(22, 'Kabupaten Tapin', 1),
(22, 'Kota Banjarbaru', 1),
(22, 'Kota Banjarmasin', 1),
(23, 'Kabupaten Berau', 1),
(23, 'Kabupaten Kutai Bara', 1),
(23, 'Kabupaten Kutai Kartanegara', 1),
(23, 'Kabupaten Kutai Timur', 1),
(23, 'Kabupaten Mahakam Ulu', 1),
(23, 'Kabupaten Paser', 1),
(23, 'Kabupaten Penajam Paser Utara', 1),
(23, 'Kota Balikpapan', 1),
(23, 'Kota Bontang', 1),
(23, 'Kota Samarinda', 1),
(24, 'Kabupaten Bulungan', 1),
(24, 'Kabupaten Malinau', 1),
(24, 'Kabupaten Nunukan', 1),
(24, 'Kabupaten Tana Tidung', 1),
(24, 'Kota Tarakan', 1),
(25, 'Kabupaten Bolaang Mongondow', 1),
(25, 'Kabupaten Bolaang Mongondow Selatan', 1),
(25, 'Kabupaten Bolaang Mongondow Timur', 1),
(25, 'Kabupaten Bolaang Mongondow Utara', 1),
(25, 'Kabupaten Kepulauan Sangihe', 1),
(25, 'Kabupaten Kepulauan Siau Tagulandang Biaro', 1),
(25, 'Kabupaten Kepulauan Talaud', 1),
(25, 'Kabupaten Minahasa', 1),
(25, 'Kabupaten Minahasa Selatan', 1),
(25, 'Kabupaten Minahasa Tenggara', 1),
(25, 'Kabupaten Minahasa Utara', 1),
(25, 'Kota Bitung', 1),
(25, 'Kota Kotamobagu', 1),
(25, 'Kota Manado', 1),
(25, 'Kota Tomohon', 1),
(26, 'Kabupaten Banggai', 1),
(26, 'Kabupaten Banggai Kepulauan', 1),
(26, 'Kabupaten Banggai Laut', 1),
(26, 'Kabupaten Buol', 1),
(26, 'Kabupaten Donggala', 1),
(26, 'Kabupaten Morowali', 1),
(26, 'Kabupaten Morowali Utara', 1),
(26, 'Kabupaten Parigi Moutong', 1),
(26, 'Kabupaten Poso', 1),
(26, 'Kabupaten Sigi', 1),
(26, 'Kabupaten Tojo Una-Una', 1),
(26, 'Kabupaten Tolitoli', 1),
(26, 'Kota Palu', 1),
(27, 'Kabupaten Bantaeng', 1),
(27, 'Kabupaten Barru', 1),
(27, 'Kabupaten Bone', 1),
(27, 'Kabupaten Bulukumba', 1),
(27, 'Kabupaten Enrekang', 1),
(27, 'Kabupaten Gowa', 1),
(27, 'Kabupaten Jeneponto', 1),
(27, 'Kabupaten Kepulauan Selayar', 1),
(27, 'Kabupaten Luwu', 1),
(27, 'Kabupaten Luwu Timur', 1),
(27, 'Kabupaten Luwu Utara', 1),
(27, 'Kabupaten Maros', 1),
(27, 'Kabupaten Pangkajene dan Kepulauan', 1),
(27, 'Kabupaten Pinrang', 1),
(27, 'Kabupaten Sidenreng Rappang', 1),
(27, 'Kabupaten Sinjai', 1),
(27, 'Kabupaten Soppeng', 1),
(27, 'Kabupaten Takalar', 1),
(27, 'Kabupaten Tana Toraja', 1),
(27, 'Kabupaten Toraja Utara', 1),
(27, 'Kabupaten Wajo', 1),
(27, 'Kota Makassar', 1),
(27, 'Kota Palopo', 1),
(27, 'Kota Parepare', 1),
(28, 'Kabupaten Bombana', 1),
(28, 'Kabupaten Buton', 1),
(28, 'Kabupaten Buton Selatan', 1),
(28, 'Kabupaten Buton Tenga', 1),
(28, 'Kabupaten Buton Utara', 1),
(28, 'Kabupaten Kolaka', 1),
(28, 'Kabupaten Kolaka Timur', 1),
(28, 'Kabupaten Kolaka Utara', 1),
(28, 'Kabupaten Konawe', 1),
(28, 'Kabupaten Konawe Kepulauan', 1),
(28, 'Kabupaten Konawe Selatan', 1),
(28, 'Kabupaten Konawe Utara', 1),
(28, 'Kabupaten Muna', 1),
(28, 'Kabupaten Muna Barat', 1),
(28, 'Kabupaten Wakatobi', 1),
(28, 'Kota Baubau', 1),
(28, 'Kota Kendari', 1),
(29, 'Kabupaten Boalemo', 1),
(29, 'Kabupaten Bone Bolango', 1),
(29, 'Kabupaten Gorontalo Utara', 1),
(29, 'Kabupaten Gorontalo', 1),
(29, 'Kabupaten Pohuwat', 1),
(29, 'Kota Gorontalo', 1),
(30, 'Kabupaten Majene', 1),
(30, 'Kabupaten Mamasa', 1),
(30, 'Kabupaten Mamuju', 1),
(30, 'Kabupaten Mamuju Tengah', 1),
(30, 'Kabupaten Pasangkayu', 1),
(30, 'Kabupaten Polewali Mandar', 1),
(31, 'Kabupaten Buru', 1),
(31, 'Kabupaten Buru Selatan', 1),
(31, 'Kabupaten Kepulauan Aru', 1),
(31, 'Kabupaten Kepulauan Tanimbar', 1),
(31, 'Kabupaten Maluku Barat Daya', 1),
(31, 'Kabupaten Maluku Tengah', 1),
(31, 'Kabupaten Maluku Tenggara', 1),
(31, 'Kabupaten Seram Bagian Barat', 1),
(31, 'Kabupaten Seram Bagian Timur', 1),
(31, 'Kabupaten Halmahera Tengah', 1),
(31, 'Kota Tual', 1),
(32, 'Kabupaten Halmahera Barat', 1),
(32, 'Kabupaten Halmahera Tengah', 1),
(32, 'Kabupaten Halmahera Timur', 1),
(32, 'Kabupaten Halmahera Selatan', 1),
(32, 'Kabupaten Halmahera Utara', 1),
(32, 'Kabupaten Kepulauan Sula', 1),
(32, 'Kabupaten Pulau Morotai', 1),
(32, 'Kabupaten Pulau Taliabu', 1),
(32, 'Kota Ternate', 1),
(32, 'Kota Tidore Kepulauan', 1),
(33, 'Kabupaten Biak Numfor', 1),
(33, 'Kabupaten Jayapura', 1),
(33, 'Kabupaten Keerom', 1),
(33, 'Kabupaten Kepulauan Yapen', 1),
(33, 'Kabupaten Mamberamo Raya', 1),
(33, 'Kabupaten Sarmi', 1),
(33, 'Kabupaten Supiori', 1),
(33, 'Kabupaten Waropen', 1),
(33, 'Kota Jayapura', 1),
(34, 'Kabupaten Fakfak', 1),
(34, 'Kabupaten Kaimana', 1),
(34, 'Kabupaten Manokwari', 1),
(34, 'Kabupaten Manokwari Selatan', 1),
(34, 'Kabupaten Pegunungan Arfak', 1),
(34, 'Kabupaten Teluk Bintuni', 1),
(34, 'Kabupaten Teluk Wondama', 1),
(35, 'Kabupaten Asmat', 1),
(35, 'Kabupaten Boven Digoel', 1),
(35, 'Kabupaten Mappi', 1),
(35, 'Kabupaten Merauke', 1),
(36, 'Kabupaten Deiyai', 1),
(36, 'Kabupaten Dogiyai', 1),
(36, 'Kabupaten Intan Jaya', 1),
(36, 'Kabupaten Mimika', 1),
(36, 'Kabupaten Nabire', 1),
(36, 'Kabupaten Paniai', 1),
(36, 'Kabupaten Puncak', 1),
(36, 'Kabupaten Puncak Jaya', 1),
(37, 'Kabupaten Jayawijaya', 1),
(37, 'Kabupaten Lanny Jaya', 1),
(37, 'Kabupaten Mamberamo Tengah', 1),
(37, 'Kabupaten Nduga', 1),
(37, 'Kabupaten Pegunungan Bintang', 1),
(37, 'Kabupaten Tolikara', 1),
(37, 'Kabupaten Yalimo', 1),
(37, 'Kabupaten Yahukimo', 1),
(38, 'Kabupaten Maybrat', 1),
(38, 'Kabupaten Raja Ampat', 1),
(38, 'Kabupaten Sorong', 1),
(38, 'Kabupaten Sorong Selatan', 1),
(38, 'Kabupaten Tambrauw', 1),
(38, 'Kota Sorong', 1);
